### ISSUE TITLE
Actualize docs and README

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#358]
- [x] `README.md` @arogachev
- [x] `src/AfterInitAttributeEventInterface.php` @arogachev
- [x] `src/DataSet/ArrayDataSet.php` @arogachev
- [x] `src/DataSet/ObjectDataSet.php` @arogachev
- [x] `src/DataSet/SingleValueDataSet.php` @arogachev
- [x] `src/DataSetInterface.php` @arogachev
- [x] `src/EmptyCriteria/NeverEmpty.php` @arogachev
- [x] `src/EmptyCriteria/WhenEmpty.php` @arogachev
- [x] `src/EmptyCriteria/WhenNull.php` @arogachev
- [x] `src/Error.php` @arogachev, @samdark #487
- [x] `src/Exception/InvalidCallbackReturnTypeException.php` @arogachev
- [x] `src/Exception/RuleHandlerInterfaceNotImplementedException.php` @arogachev
- [x] `src/Exception/RuleHandlerNotFoundException.php` @arogachev
- [x] `src/Exception/UnexpectedRuleException.php` @arogachev
- [x] `src/Helper/DataSetNormalizer.php` @arogachev
- [x] `src/Helper/ObjectParser.php` @arogachev
- [x] `src/Helper/RulesNormalizer.php` @arogachev #506
- [x] `src/Helper/SkipOnEmptyNormalizer.php` @arogachev
- [x] `src/LimitInterface.php` @arogachev
- [x] `src/PostValidationHookInterface.php` @arogachev
- [x] `src/PropagateOptionsInterface.php` @arogachev
- [x] `src/Result.php` @samdark #487
- [x] `src/Rule/AtLeast.php`@samdark #489
- [x] `src/Rule/AtLeastHandler.php` @samdark #489
- [x] `src/Rule/Boolean.php` @arogachev #485
- [x] `src/Rule/BooleanHandler.php` @arogachev #485 
- [x] `src/Rule/Callback.php` @samdark #489
- [x] `src/Rule/CallbackHandler.php` @samdark #489
- [x] `src/Rule/Compare.php` @samdark #489
- [x] `src/Rule/CompareHandler.php` @samdark #489
- [x] `src/Rule/CompareTo.php` @samdark #489
- [x] `src/Rule/Composite.php` @arogachev #496
- [x] `src/Rule/CompositeHandler.php` @arogachev #496
- [x] `src/Rule/Count.php` @samdark #489
- [x] `src/Rule/CountHandler.php` @samdark #489
- [x] `src/Rule/Each.php` @arogachev #496
- [x] `src/Rule/EachHandler.php` @arogachev #496
- [x] `src/Rule/Email.php` @samdark #477
- [x] `src/Rule/EmailHandler.php` @samdark #477
- [x] `src/Rule/Equal.php` @samdark #489
- [x] `src/Rule/GreaterThan.php` @samdark #489
- [x] `src/Rule/GreaterThanOrEqual.php` @samdark #489
- [x] `src/Rule/HasLength.php` @samdark #490
- [x] `src/Rule/HasLengthHandler.php` @samdark #490
- [x] `src/Rule/In.php` @samdark #490
- [x] `src/Rule/InHandler.php` @samdark #490
- [x] `src/Rule/Ip.php` @samdark #475
- [x] `src/Rule/IpHandler.php` @samdark #475
- [x] `src/Rule/IsTrue.php` @arogachev #485
- [x] `src/Rule/IsTrueHandler.php` @arogachev #485
- [x] `src/Rule/Json.php` @arogachev #493
- [x] `src/Rule/JsonHandler.php` @arogachev #493
- [x] `src/Rule/LessThan.php` @samdark #489
- [x] `src/Rule/LessThanOrEqual.php` @samdark #489
- [x] `src/Rule/Nested.php` @arogachev #505
- [x] `src/Rule/NestedHandler.php` @arogachev #505
- [x] `src/Rule/NotEqual.php` @samdark #489
- [x] `src/Rule/Number.php` @samdark #490
- [x] `src/Rule/NumberHandler.php` @samdark #490
- [x] `src/Rule/Regex.php` @samdark #490
- [x] `src/Rule/RegexHandler.php` @samdark #490
- [x] `src/Rule/Required.php` @arogachev #493
- [x] `src/Rule/RequiredHandler.php` @arogachev #493
- [x] `src/Rule/StopOnError.php` @arogachev #496
- [x] `src/Rule/StopOnErrorHandler.php` @arogachev #496
- [x] `src/Rule/Subset.php` @arogachev #493
- [x] `src/Rule/SubsetHandler.php` @arogachev #493
- [x] `src/Rule/Trait/LimitHandlerTrait.php` @arogachev
- [x] `src/Rule/Trait/LimitTrait.php` @arogachev
- [x] `src/Rule/Trait/SkipOnEmptyTrait.php` @arogachev
- [x] `src/Rule/Trait/SkipOnErrorTrait.php` @arogachev
- [x] `src/Rule/Trait/WhenTrait.php` @arogachev
- [x] `src/Rule/Url.php` @samdark #474
- [x] `src/Rule/UrlHandler.php` @samdark #474
- [x] `src/RuleHandlerContainer.php` @arogachev
- [x] `src/RuleHandlerInterface.php` @arogachev
- [x] `src/RuleHandlerResolverInterface.php` @arogachev
- [x] `src/RuleInterface.php` @arogachev
- [x] `src/RulesDumper.php` @samdark #487
- [x] `src/RulesProvider/AttributesRulesProvider.php` @arogachev
- [x] `src/RulesProviderInterface.php` @samdark #487
- [x] `src/SerializableRuleInterface.php` @arogachev
- [x] `src/SimpleRuleHandlerContainer.php` @arogachev
- [x] `src/SkipOnEmptyInterface.php` @arogachev
- [x] `src/SkipOnErrorInterface.php` @arogachev
- [x] `src/ValidationContext.php` @samdark #473
- [x] `src/Validator.php` @arogachev #485
- [x] `src/ValidatorInterface.php` @arogachev #483
- [x] `src/WhenInterface.php` @arogachev

Deleted:

- [x] `src/Rule/Trait/PreValidateTrait.php` @arogachev

New:

- [x] `src/Helper/PropagateOptionsHelper.php` @arogachev
- [x] `src/Helper/RulesNormalizerIterator.php` @arogachev #506
- [x] `src/AttributeTranslator/ArrayAttributeTranslator.php` @samdark #473
- [x] `src/AttributeTranslator/NullAttributeTranslator.php` @samdark #473
- [x] `src/AttributeTranslator/TranslatorAttributeTranslator.php` @samdark
- [x] `src/AttributeTranslatorInterface.php` @samdark #473
- [x] `src/AttributeTranslatorProviderInterface.php` @samdark #473
